name: py36
channels:
  - anaconda
  - conda-forge
dependencies:
  - python =3.6
  - pytest >=3.7
  - jupyterlab
  - matplotlib
  - pandas
  - networkx
  - sqlalchemy
  - psycopg2
  - bokeh
  - holoviews
  - flask
  - scikit-learn
  - requests
